name: Zizi Bot

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/WinTenBot/Zizi.Bot

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
      - name: Install dependencies
        run: dotnet restore
        
      - name: Linux64 Build
        run: dotnet publish -r linux-x64 -c Release --self-contained=false /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true

      - name: Windows64 Build
        run: dotnet publish -r win-x64 -c Release --self-contained=false /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true

      - name: Upload Linux64 Artifacs
        uses: actions/upload-artifact@v2.1.4
        with:
          name: zizibot-linux64-build
          path: src/WinTenBot/Zizi.Bot/bin/Release/net5.0/linux-x64/publish
          
      - name: Upload Linux64 Artifacs
        uses: actions/upload-artifact@v2.1.4
        with:
          name: zizibot-windows-build
          path: src/WinTenBot/Zizi.Bot/bin/Release/net5.0/win-x64/publish
